ecosante/newsletter/models/newsletter_hebdo_template.py
from dataclasses import dataclass
from datetime import date, datetime
from psycopg2.extras import DateRange
from sqlalchemy.sql.expression import cast
from sqlalchemy.dialects.postgresql import DATERANGE
from sqlalchemy.dialects import postgresql
from typing import Dict, List

from ecosante.extensions import db
from ecosante.inscription.models import Inscription

def property_indicateur(indicateur):
    return property(
        lambda self: self.indicateur_getter(indicateur),
        lambda self, value: self.indicateur_setter(value, indicateur)
    )

@dataclass
class NewsletterHebdoTemplate(db.Model):
    id: int = db.Column(db.Integer, primary_key=True)
    sib_id: int = db.Column(db.Integer, nullable=False)
    ordre: int = db.Column(db.Integer, nullable=False)

    deplacement: List[str] = db.Column(postgresql.ARRAY(db.String))
    activites: List[str] = db.Column(postgresql.ARRAY(db.String))
    _enfants: List[str] = db.Column("enfants", postgresql.ARRAY(db.String))
    chauffage: List[str] = db.Column(postgresql.ARRAY(db.String))
    _animaux_domestiques: List[str] = db.Column("animaux_domestiques", postgresql.ARRAY(db.String))
    indicateurs: List[str] = db.Column(postgresql.ARRAY(db.String))
    indicateurs_exclus: List[str] = db.Column(postgresql.ARRAY(db.String))

    _periode_validite: DateRange = db.Column(
        "periode_validite",
        DATERANGE(),
        nullable=False,
        default=lambda: DateRange('2022-01-01', '2023-01-01')
    )

    @classmethod
    def get_templates(cls):
        return cls.query.order_by(cls.ordre).all()

    def filtre_date(self, date_):
        periode_validite = self.periode_validite
        if periode_validite.lower.year != periode_validite.upper.year:
            return date(date_.year, 1, 1) <= date_ <= periode_validite.upper.replace(year=date_.year)\
                 or  periode_validite.lower.replace(year=date_.year) <= date_ <= date(date_.year, 12, 31)
        return date_ in self.periode_validite

    def filtre_criteres(self, inscription):
        if self.ordre > 0:
            return False
        for nom_critere in ['chauffage', 'activites', 'deplacement']:
            critere = getattr(self, nom_critere)
            if isinstance(critere, list) and len(critere) > 0:
                if nom_critere == 'activites':
                    critere = list(map(lambda x: x.replace('activite_physique', 'sport'), critere))
                inscription_critere = getattr(inscription, nom_critere)
                if not isinstance(inscription_critere, list):
                    return False
                if len(set(critere).intersection(inscription_critere)) == 0:
                    return False
        if isinstance(self.enfants, bool) and self.enfants != inscription.has_enfants:
            return False
        if isinstance(self.animaux_domestiques, bool) and self.animaux_domestiques != inscription.has_animaux_domestiques:
            return False
        inscription_indicateurs = inscription.indicateurs if isinstance(inscription.indicateurs, list) else []
        self_indicateurs = self.indicateurs if isinstance(self.indicateurs, list) else []
        self_indicateurs_exclus = self.indicateurs_exclus if isinstance(self.indicateurs_exclus, list) else []
        if not all([indicateur in inscription_indicateurs for indicateur in self_indicateurs]):
            return False
        if any([indicateur in inscription_indicateurs for indicateur in self_indicateurs_exclus]):
            return False
        return True

    @classmethod
    def next_template(cls, inscription: Inscription, templates=None) -> 'NewsletterHebdoTemplate | None':
        templates = templates or cls.get_templates()
        template_id_ordre = {t.id: t.ordre for t in templates}
        already_sent_templates_ordres = [
            template_id_ordre[nl.newsletter_hebdo_template_id] 
            for nl in inscription.last_newsletters_hebdo
        ]
        valid_templates = sorted(
            [
                t
                for t in templates
                if t.filtre_date(date.today())\
                    and t.ordre not in already_sent_templates_ordres
                    and t.filtre_criteres(inscription)\
            ],
            key=lambda t: t.ordre
        )
        if len(valid_templates) == 0:
            return None

        return [t for t in valid_templates][0]

    @property
    def periode_validite(self) -> DateRange:
        current_year = datetime.today().year
        if self._periode_validite.lower.replace(year=current_year) <= self._periode_validite.upper.replace(year=current_year):
            year_lower = current_year
        else:
            year_lower = current_year - 1
        # Si les dates sont sur deux années différentes ont veut conserver le saut d’année
        year_upper = year_lower + (self._periode_validite.upper.year - self._periode_validite.lower.year)
        return DateRange(self._periode_validite.lower.replace(year=year_lower), self._periode_validite.upper.replace(year=year_upper))

    @property
    def debut_periode_validite(self):
        return self.periode_validite.lower
    @debut_periode_validite.setter
    def debut_periode_validite(self, value):
        self._periode_validite = DateRange(
            value,
            self._periode_validite.upper if self._periode_validite else None)

    @property
    def fin_periode_validite(self):
        return self.periode_validite.upper
    @fin_periode_validite.setter
    def fin_periode_validite(self, value):
        self._periode_validite = DateRange(
            self._periode_validite.lower if self._periode_validite else None,
            value
        )

    @property
    def animaux_domestiques(self):
        if isinstance(self._animaux_domestiques, list):
            return self._animaux_domestiques[0] == 'true' if self._animaux_domestiques else False
        return None
    @animaux_domestiques.setter
    def animaux_domestiques(self, value):
        if isinstance(value, bool):
            self._animaux_domestiques = ["true" if value else "false"]
        else:
            self._animaux_domestiques = None

    @property
    def enfants(self):
        if isinstance(self._enfants, list):
            return self._enfants[0] == 'true' if self._enfants else False
        return None
    @enfants.setter
    def enfants(self, value):
        if isinstance(value, bool):
            self._enfants = ["true" if value else "false"]
        else:
            self._enfants = None

    def indicateur_setter(self, value, indicateur):
        if value == None:
            self.indicateurs = list(set(self.indicateurs or []) - set([indicateur]))
            self.indicateurs_exclus = list(set(self.indicateurs_exclus or []) - set([indicateur]))
        elif value == False:
            self.indicateurs = list(set(self.indicateurs or []) - set([indicateur]))
            self.indicateurs_exclus = list(set(self.indicateurs_exclus or []) | set([indicateur]))
        elif value == True:
            self.indicateurs = list(set(self.indicateurs or []) | set([indicateur]))
            self.indicateurs_exclus = list(set(self.indicateurs_exclus or []) - set([indicateur]))

    def indicateur_getter(self, indicateur):
        if not type(self.indicateurs) in [list, None]:
            return None
        if indicateur in (self.indicateurs or []):
            return True
        if not type(self.indicateurs_exclus) in [list, None]:
            return None
        if indicateur in (self.indicateurs_exclus or []):
            return False
        return None

    raep = property_indicateur("raep")
    indice_atmo = property_indicateur("indice_atmo")
    vigilance_meteo = property_indicateur("vigilance_meteo")
    indice_uv = property_indicateur("indice_uv")

ecosante/newsletter/forms/newsletter_hebdo.py
from wtforms.fields.simple import BooleanField, HiddenField
from wtforms import ValidationError
from wtforms.fields import DateField
from wtforms.form import Form
from ecosante.utils.form import BaseForm, IntegerField, MultiCheckboxField, OuiNonField
from ecosante.newsletter.models import NewsletterHebdoTemplate
from datetime import date
from ecosante.recommandations.forms.edit import FormEdit

class FormTemplateAdd(BaseForm):
    sib_id = IntegerField("ID send in blue")
    ordre = IntegerField("Ordre d’envoi (si l’ordre est en dessous de 0 la NL ne sera pas envoyé, c’est utile pour les brouillons)")
    debut_periode_validite = DateField("Début de la période de validité", default=date.today().replace(month=1, day=1))
    fin_periode_validite = DateField("Fin de la période de validité", default=date.today().replace(month=1, day=1, year=date.today().year+1))

    activites = FormEdit.activites
    enfants = OuiNonField("Enfants (de moins de 6 ans) ?")
    chauffage = FormEdit.chauffage
    deplacement = FormEdit.deplacement
    animaux_domestiques = FormEdit.animal_de_compagnie

    indice_atmo = OuiNonField("Inclure (Oui) ou exclure (Non) les abonnés à l’indice ATMO ?")
    raep = OuiNonField("Inclure (Oui) ou exclure (Non) les abonnés RAEP ?")
    vigilance_meteo = OuiNonField("Inclure (Oui) ou exclure (Non) les abonnés à la vigilance météo ?")
    indice_uv = OuiNonField("Inclure (Oui) ou exclure (Non) les abonnés à l’indice UV ?")

class FormTemplateEdit(FormTemplateAdd):
    id = HiddenField()

ecosante/newsletter/blueprint.py
from flask import (
    abort,
    current_app,
    render_template,
    request,
    redirect,
    url_for,
    stream_with_context,
)
from flask.helpers import flash
from flask.wrappers import Response
from datetime import datetime, timedelta, date
from calendar import THURSDAY
import csv

from indice_pollution.helpers import today
from indice_pollution.history.models.commune import Commune
from indice_pollution.history.models.departement import Departement
from indice_pollution.history.models.vigilance_meteo import VigilanceMeteo
from indice_pollution.history.models.indice_uv import IndiceUv
from sqlalchemy.orm import joinedload
from sqlalchemy import func, funcfilter
from ecosante.inscription.models import Inscription
from ecosante.recommandations.models import Recommandation

from ecosante.utils import Blueprint
from ecosante.extensions import db, sib, admin_authenticator
from .forms import FormTemplateAdd, FormTemplateEdit
from .models import Newsletter, NewsletterDB, NewsletterHebdoTemplate
from .tasks.import_in_sb import import_
from .tasks.send_webpush_notifications import send_webpush_notification, vapid_claims
from indice_pollution.history.models import IndiceATMO
import sib_api_v3_sdk
from psycopg2.extras import DateTimeTZRange

bp = Blueprint("newsletter", __name__)

@bp.route('<short_id>/avis', methods=['POST'])
def avis(short_id):
    nl = db.session.query(NewsletterDB).filter_by(short_id=short_id).first()
    if not nl:
        abort(404)
    nl.appliquee = request.args.get('avis') == 'oui' or request.args.get('appliquee') == 'oui'
    db.session.add(nl)
    db.session.commit()
    return {
        "short_id": nl.short_id,
        "avis": nl.avis,
        "recommandation": nl.recommandation,
        "appliquee": nl.appliquee
    }

@bp.route('/avis/liste')
@admin_authenticator.route
def liste_avis():
    offset = (date.today().weekday() - THURSDAY) % 7
    last_thursday = date.today() - timedelta(days=offset)
    liste_avis_hebdos = db.session.query(\
                NewsletterDB.newsletter_hebdo_template_id,
                NewsletterHebdoTemplate.sib_id,
                func.count('1').label('nb_envois'),
                funcfilter(func.count('1'), NewsletterDB.appliquee.is_(True)).label('nb_avis_positifs'),
                funcfilter(func.count('1'), NewsletterDB.appliquee.is_not(None)).label('nb_avis'),
                funcfilter(func.count('&'), NewsletterDB.date == last_thursday).label('nb_envois_semaine_passee')
            )\
            .join(NewsletterHebdoTemplate)\
            .filter(
                NewsletterDB.newsletter_hebdo_template_id.is_not(None))\
            .group_by(NewsletterDB.newsletter_hebdo_template_id, NewsletterHebdoTemplate.sib_id)\
            .all()
    nb_avis = sum(i['nb_avis'] for i in liste_avis_hebdos)
    nb_avis_positifs = sum(i['nb_avis_positifs'] for i in liste_avis_hebdos)
    nb_envois = sum(i['nb_envois'] for i in liste_avis_hebdos)

    return render_template(
        'liste_avis.html',
        liste_avis_hebdos=liste_avis_hebdos,
        nb_avis=nb_avis,
        nb_avis_positifs=nb_avis_positifs,
        nb_envois=nb_envois,
        sib_api_key=sib.configuration.api_key['api-key']
    )


@bp.route('/test', methods=['GET', 'POST'])
@admin_authenticator.route
def test():
    if request.method == "GET":
        return render_template("test.html")
    indice_atmo = int(request.form.get("indice_atmo"))
    uid = request.form.get("uid")
    inscription = Inscription.query.filter_by(uid=uid).first()
    nb_mails = 0
    nb_notifications = 0
    nb_notifications_sent = 0
    phenomene_to_phenomene_id = {v: k for k, v in VigilanceMeteo.phenomenes.items()}
    couleur_to_couleur_id = {v: k for k, v in VigilanceMeteo.couleurs.items()}
    recommandations = Recommandation.published_query().all()
    indice_uv = IndiceUv()
    indice_uv.uv_jo = request.form.get("indice_uv", type=int)
    for media in inscription.indicateurs_media:
        nl = Newsletter(
            inscription=inscription,
            forecast={"data":[{"date": str(today()), "label": IndiceATMO.label_from_valeur(indice_atmo), "couleur": IndiceATMO.couleur_from_valeur(indice_atmo)}]},
            raep=int(request.form.get("raep")),
            allergenes={k: v for k, v in zip(request.form.getlist('allergene_nom[]'), request.form.getlist('allergene_value[]'))},
            validite_raep={
                "debut": today().strftime("%d/%m/%Y"),
                "fin": (today()+timedelta(days=7)).strftime("%d/%m/%Y")
            },
            vigilances=Newsletter.get_vigilances_recommandations(
                [
                    VigilanceMeteo(
                        zone_id=inscription.commune.departement.zone_id,
                        couleur_id=couleur_to_couleur_id[c],
                        phenomene_id=phenomene_to_phenomene_id[ph],
                        date_export=datetime.now() - timedelta(minutes=30),
                        validity=DateTimeTZRange(datetime.now() - timedelta(hours=6), datetime.now() + timedelta(hours=6)),
                    )
                    for c, ph in zip(
                        request.form.getlist('vigilance_couleur[]'),
                        request.form.getlist('vigilance_phenomene[]')
                    )
                ],
                recommandations
            ),
            recommandations=recommandations,
            indice_uv=indice_uv
        )
        if media == "mail":
            import_(None, newsletters=[nl], force_send=True, test=True)
            nb_mails += 1
        elif media == "notifications_web":
            for wp in inscription.webpush_subscriptions_info:
                nl.webpush_subscription_info = wp
                nl.webpush_subscription_info_id = wp.id
                if send_webpush_notification(NewsletterDB(nl), vapid_claims):
                    nb_notifications_sent += 1
                nb_notifications += 1

    return render_template("test_ok.html", nb_mails=nb_mails, nb_notifications=nb_notifications, nb_notifications_sent=nb_notifications_sent)

@bp.route('/newsletter_hebdo_templates', methods=['GET', 'POST'])
@admin_authenticator.route
def newsletter_hebdo():
    templates_db = NewsletterHebdoTemplate.query.order_by(NewsletterHebdoTemplate.ordre).all()
    templates = []
    api_instance = sib_api_v3_sdk.TransactionalEmailsApi(sib)
    for t in templates_db:
        template = {"db": t, "is_active": False}
        try:
            api_response = api_instance.get_smtp_template(t.sib_id)
            template["is_active"] = api_response.is_active
        except sib_api_v3_sdk.rest.ApiException as e:
            current_app.logger.info(f"Template SIB {t.sib_id} inexistant")
            pass
        templates.append(template)
    return render_template("newsletter_hebdo_templates.html", templates=templates)


@bp.route('/newsletter_hebdo/_add', methods=['GET', 'POST'])
@bp.route('/newsletter_hebdo/<int:id_>/_edit', methods=['GET', 'POST'])
@admin_authenticator.route
def newsletter_hebdo_form(id_=None):
    form_cls = FormTemplateEdit if id_ else FormTemplateAdd
    form = form_cls(obj=NewsletterHebdoTemplate.query.get(id_))
    (dernier_ordre,) = db.session.query(func.max(NewsletterHebdoTemplate.ordre)).first()
    form.ordre.description = f"Dernier ordre ajouté : {dernier_ordre}"
    if request.method == "GET":
        return render_template("newsletter_hebdo_form.html", form=form)
    else:
        if form.validate_on_submit():
            template = NewsletterHebdoTemplate.query.get(id_) or NewsletterHebdoTemplate()
            form.populate_obj(template)
            db.session.add(template)
            db.session.commit()
            flash(
                "Template édité !" if id_ else "Template ajouté"
            )
            return redirect(url_for("newsletter.newsletter_hebdo"))
        else:
	        return render_template("newsletter_hebdo_form.html", form=form)

ecosante/newsletter/templates/export.html
{% extends 'base_form.html'%}

{% block pre_form %}

{% scss "newsletter/css/recommandations.scss" %}
  <link href="{{ ASSET_URL }}" rel="stylesheet">
{% endassets %}

{% endblock pre_form %}

{% block block_form %}
Rechercher : <input type="text" id="search">
<form method="POST" novalidate>
    {{ form.hidden_tag() }}
    <div class="form__group">
        <button class="button" type="submit" id="submit">Obtenir un export</button>
        <a href="{{url_for("inscription.import_")}}">Importer une liste dans sendinblue</a>
    </div>
    {{ render_field(form.recommandations) }}
    <div class="form__group">
        <button class="button" type="submit" id="submit">Obtenir un export</button>
    </div>
</form>

{% rollupjs "newsletter/js/search.js" %}
<script src="{{ ASSET_URL}}"></script>
{% endassets %}

{% endblock block_form %}

ecosante/newsletter/templates/liste_avis.html
{% extends 'base_admin.html' %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="main">
            <h1>Avis sur la newsletter hebdo</h1>
            <div class="section section-grey">
                <div class="container">
                    <div class="tiles">
                        <div class="grid">
                            <div class="tile">
                                <div class="tile__icon">Nombre d’envois</div>
                                <h3>{{ nb_envois }}</h3>
                            </div>
                            <div class="tile">
                                <div class="tile__icon">Nombre d’avis</div>
                                <h3>{{ nb_avis }}</h3>
                            </div>
                            <div class="tile">
                                <div class="tile__icon">Nombre d’avis positifs</div>
                                <h3>{{ nb_avis_positifs }}</h3>
                            </div>
                            <div class="tile">
                                <div class="tile__icon">Proportion d’avis positifs</div>
                                <h3>{{ (100 * (nb_avis_positifs / nb_avis))|round(2) if nb_avis else '-' }} %</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section">
                <div class="panel">
                <h2>Avis par newsletters</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th class="ascending">Newsletter</th>
                            <th>Nombre d’envois</th>
                            <th>Nombre d’envois la semaine passée</th>
                            <th>Nombre d’avis</th>
                            <th>Nombre d’avis positifs</th>
                            <th>Proportion d’avis positifs</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for nl in liste_avis_hebdos %}
                        <tr>
                            <td><a href="https://my.sendinblue.com/camp/template/{{ nl.sib_id }}/message-setup" target="_blank">{{ nl.sib_id }}</a></td>
                            <td>{{ nl.nb_envois }}</td>
                            <td>{{ nl.nb_envois_semaine_passee }}</td>
                            <td>{{ nl.nb_avis }}</td>
                            <td>{{ nl.nb_avis_positifs }}</td>
                            <td>{{ (100 * (nl.nb_avis_positifs / nl.nb_avis))|round(2) if nl.nb_avis else '-' }} %</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
        </div>        
    </div>
</section>
<style>
    .table thead th.ascending:hover::after {
        content: "▼";
        color: grey;
    }
    .table thead th:not(.ascending):hover::after {
        content: "▲";
        color: grey;
    }
</style>
<script type="text/javascript">

    let sortTable = (table, col) => {
        var tb = table.tBodies[0], // use `<tbody>` to ignore `<thead>` and `<tfoot>` rows
            tr = Array.prototype.slice.call(tb.rows, 0), // put rows into array
            i;
        let th = table.tHead.rows[0].cells[col];
        let reverse = th.classList.contains('ascending') ? -1 : 1;
        tr = tr.sort(function (a, b) { // sort rows
            let match_groups_a = a.cells[col].textContent.trim().match(/[+-]?([0-9]*[.])?[0-9]+/);
            let match_groups_b = b.cells[col].textContent.trim().match(/[+-]?([0-9]*[.])?[0-9]+/);
            let a_value = match_groups_a === null ? Infinity : match_groups_a[0];
            let b_value = match_groups_b === null ? Infinity : match_groups_b[0];
            if (a_value === b_value === Infinity) {
                return 0;
            }
            return reverse * (parseFloat(a_value) - parseFloat(b_value))
        });
        for(i = 0; i < tr.length; ++i) tb.appendChild(tr[i]); // append each row in order
        for (const [idx, th] of Array.from(table.tHead.rows[0].cells).entries()) {
            th.classList.remove('ascending');
            th.classList.remove('descending');
            if (idx === col) {
                th.classList.add(reverse == 1 ? 'ascending' : 'descending')
            }
        }
    }

    window.onload = () => {
        const options = {
            method: 'GET',
            headers: {
              accept: 'application/json',
              'api-key': '{{ sib_api_key }}'
            }
        };
        let table = document.querySelector('table')
        Array.from(table.tBodies[0].rows).forEach(
	        tr => {
                let innera = tr.cells[0].children[0]
                fetch(`https://api.sendinblue.com/v3/smtp/templates/${innera.innerHTML}`, options)
                    .then(response => response.json())
                    .then(response => {
                        innera.innerHTML = response.name
                    })
                    .catch(err => console.error(err));
            }
        )
        let ths = table.tHead.rows[0].cells;
        for (const [idx, th] of Array.from(ths).entries()) {
            th.addEventListener('click', () => sortTable(table, idx))
        }
    }
</script>
{% endblock content %}

ecosante/newsletter/templates/newsletter_hebdo_form.html
{% extends "base_admin_form.html" %}

{% block block_form %}

<div class="section">
  <div class="container">
    <div class="panel">
      <form method="POST">
        {{ form.hidden_tag() }}
        {{ render_field(form.sib_id)}}
        {{ render_field(form.ordre)}}
        {{ render_field(form.debut_periode_validite)}}
        {{ render_field(form.fin_periode_validite)}}

        {{ render_field(form.activites) }}
        {{ render_field(form.chauffage) }}
        {{ render_field(form.deplacement) }}
        {{ render_field(form.animaux_domestiques) }}
        {{ render_field(form.enfants) }}
        {{ render_field(form.indice_atmo) }}
        {{ render_field(form.raep) }}
        {{ render_field(form.vigilance_meteo) }}
        {{ render_field(form.indice_uv) }}

        <div class="form__group">
          <button class="button" type="submit" id="submit">Envoyer</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

ecosante/newsletter/templates/newsletter_hebdo_templates.html
{% extends "base_admin.html" %}

{% block content %}
  <div class="section">
    <div class="panel">
      <a href="{{ url_for("newsletter.newsletter_hebdo_form") }}">Ajouter un template</a>
      <table class="table">
        <thead>
          <tr>
            <td>ID Send in blue</td>
            <td>Ordre</td>
            <td>Actif</td>
            <td>Édition</td>
          </tr>
        </thead>
        <tbody>
          {% for template in templates %}
            <tr>
              <td><a href="https://my.sendinblue.com/camp/template/{{template.db.sib_id}}/message-setup" target="_blank">{{ template.db.sib_id }}</a></td>
              <td>{{ template.db.ordre }}</td>
              <td>{{ "✅" if template.is_active else "❌" }}</td>
              <td><a href="{{ url_for("newsletter.newsletter_hebdo_form", id_=template.db.id) }}">Edition</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

ecosante/newsletter/templates/send.html
{% extends "base.html" %}

{% block content %}

<section class="section">
<h1>Import dans send in blue</h1>
<div class="container">
<div id="progress"></div>
<div id="progress_details"></div>
</div>
</section>

<script type="application/json" id="task_id">{"task_id": "{{ task_id }}" }</script>
{% rollupjs "newsletter/js/get_task_status.js" %}
<script type="application/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% endblock content %}

ecosante/newsletter/templates/task_status_display.html
{% extends "base.html" %}

{% block content %}

<section class="section">
<h1>Import dans send in blue</h1>
<div class="container">

<div id="progress">
    <progress max="100"></progress>
    <span id="progress_display"></span>
</div>
<div id="progress_details"></div>
</div>
</section>

<script type="application/json" id="task_status_url">{"task_status_url": "{{ task_status_url }}" }</script>
{% rollupjs "newsletter/js/get_task_status.js" %}
<script type="application/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% endblock content %}

ecosante/newsletter/templates/test_ok.html
{% extends "base_admin.html" %}
{% block content %}
<div class="section">
	<div class="container">
		<h1>Newsletter envoyée ( {{ nb_mails }} mails, {{ nb_notifications }} notifications dont {{ nb_notifications_sent }} avec succès</h1>
		<h2>💌</h2>
	</div>
</div>
{% endblock content %}