ecosante/recommandations/forms/edit.py
from jinja2.nodes import Mul
from wtforms.fields import IntegerField, SelectField
from ecosante.utils.form import RadioField, BaseForm, OuiNonField, MultiCheckboxField, IntegerField, coerce_int
from wtforms import TextAreaField, HiddenField

class FormAdd(BaseForm):
    status = RadioField(
        "Statut",
        choices=[
            ('draft', 'Brouillon'),
            ('published', 'Publiée'),
            ('hidden', 'Non publiée')
        ]
    )
    recommandation = TextAreaField('Recommandation')
    precisions = TextAreaField('Précisions')
    type_ = RadioField(
        'Type',
        choices=[
            ("indice_atmo", "Indice ATMO"),
            ("episode_pollution", "Épisode de pollution"),
            ("pollens", "Pollens"),
            ("radon", "Radon"),
            ("vigilance_meteo", "Vigilance météo"),
            ("indice_uv", "Indice UV"),
            ("baignades", "Eaux de baignade")
        ]
    )
    saison = MultiCheckboxField("Montrer la recommandation que durant les saisons :",
        choices=[
            ('hiver', 'Hiver'),
            ('printemps', 'Printemps'),
            ('ete', 'Été'),
            ('automne', 'Automne'),
        ]
    )
    qa = MultiCheckboxField(
        "Montrer en cas d’indice ATMO :",
        choices=[('bonne', 'bon à moyen'), ('mauvaise', 'dégradé à extrêment mauvais'), ('evenement', 'Évévement')]
    )
    polluants = MultiCheckboxField(
        "Montrer en cas d’épisode de pollution :",
        description="seuil «information ou recommandation» ou «alerte»",
        choices=[
            ('ozone', 'à l’ozone'),
            ('dioxyde_azote', 'au dioxyde d’azote'),
            ('dioxyde_soufre', 'au dioxyde de soufre'),
            ('particules_fines', 'aux particules fines')
        ]
    )
    etat_episode_pollution = SelectField(
        'État épisode de pollution',
        choices=[(None, ""), ("information", "Information"), ("alerte", "Alerte")],
    )
    min_raep = SelectField(
        'Montrer pour un raep',
        choices=[(0, "de 0"), (1, "de 1 à 3"), (4, "4 à 6")],
        coerce=int
    )
    population = MultiCheckboxField(
        "Montrer aux populations suivantes :",
        choices=[
            ('enfants', 'Enfants (de moins de 6 ans)'),
            ('personnes_sensibles', 'personnes sensibles/vulnérables à la QA'),
            ('autres', 'Autres')
        ]
    )
    activites = MultiCheckboxField(
        "Montrer pour les activités suivantes :",
        choices=[
            ('menage', 'Ménage'),
            ('bricolage', 'Bricolage'),
            ('jardinage', 'Jardinage'),
            ('activite_physique', 'Activité physique')
        ]
    )
    deplacement = MultiCheckboxField(
        "Montrer pour les modes de déplacement suivants :",
        choices=[
            ("velo", "Vélo"),
            ("tec", "Transport en commun"),
            ("voiture", "Voiture")
        ]
    )
    chauffage = MultiCheckboxField(
        "Chauffage",
        choices=[
            ("bois", "Cheminée, insert ou poêle à bois"),
            ("chaudiere", "Chaudière au fioul, au gaz ou électrique"),
            ("appoint", "Chauffage mobile d’appoint au fioul"),
        ]
    )
    animal_de_compagnie = OuiNonField("Animal de compagnie")
    sources = TextAreaField("Sources")
    categorie = TextAreaField("Catégorie")
    ordre = IntegerField("Ordre", description="Si renseigné, une recommandation avec un ordre plus petit sera donnée à l’utilisateur avant celle d’un ordre plus grand. Si pour une journée deux recommandations avec le même ordre sont possibles, l’une ou l’autre sera donnée.")
    potentiel_radon = MultiCheckboxField(
        "Potentiel Radon associé",
        choices=[
            ("", "Aucun"),
            (1, "Catégorie 1"),
            (2, "Catégorie 2"),
            (3, "Catégorie 3")
        ],
        coerce=coerce_int
    )

    vigilance_couleur_ids = MultiCheckboxField(
        "Niveau de vigilance",
        choices=[
            (1, "Verte"),
            (2, "Jaune"),
            (3, "Orange"),
            (4, "Rouge")
        ],
        coerce=coerce_int
    )

    vigilance_phenomene_ids = MultiCheckboxField(
        "Phénomène",
        choices=[
            (1, "Vent"),
            (2, "Pluie-Inondantion"),
            (3, "Orages"),
            (4, "Crues"),
            (5, "Neige"),
            (6, "Canicule"),
            (7, "Grand Froid"),
            (8, "Avalanches"),
            (9, "Vagues-Submersion")
        ],
        coerce=coerce_int
    )

    min_indice_uv = SelectField(
        'Montrer pour un indice UV',
        choices=[(0, "de 0") ,(1, "de 1 à 2"),  (3, "de 3 à 5"), (6, "de 6 à 7"), (8, "de 8 à 10"), (11, "de 11 et plus")],
        coerce=int
    )

    def validate(self, extra_validators=[]):
        rv = super().validate(extra_validators=extra_validators)
        if not self.qa.data and not self.polluants.data and self.type_.data == "indice_atmo":# and not self.raep.data:
            rv = False
            self.qa.errors = ["Vous devez remplir soit une qualité de l’air, soit un pic de pollution, sinon la recommandation n’est jamais envoyée"]
        return rv


class FormEdit(FormAdd):
    id = HiddenField("id")

ecosante/recommandations/blueprint.py
from flask.globals import current_app
from flask.helpers import make_response
from ecosante.pages.blueprint import admin
from flask import (
    render_template,
    abort,
    jsonify,
    request,
    url_for,
    redirect,
    flash,
    stream_with_context
)
from ecosante.extensions import admin_authenticator
from flask.wrappers import Response
from datetime import datetime
from itertools import chain
from .models import Recommandation, db
from ecosante.newsletter.models import NewsletterDB
from .forms import FormAdd, FormEdit, FormSearch
from ecosante.utils import Blueprint
from ecosante.utils.funcs import generate_line
from sqlalchemy import or_, func

bp = Blueprint(
    "recommandations",
    __name__,
)

@bp.route('_list')
def list_recommandations():
    form = FormSearch(request.args)
    query = make_query(form)
    return jsonify(query.filter(Recommandation.status=="published").all())

@bp.route('_rendu_markdown', methods=['POST'])
def rendu_markdown():
    return Recommandation.sanitizer(request.form.get('to_render'))

@bp.route('add', methods=['GET', 'POST'])
@admin_authenticator.route
def add():
    form = FormAdd()
    if request.method == "POST":
        recommandation = Recommandation()
        form.populate_obj(recommandation)
        db.session.add(recommandation)
        db.session.commit()
        flash("Recommandation ajoutée")
        return redirect(url_for("recommandations.list_"))
    return render_template(
        "edit.html",
        form=form,
        action="Ajouter"
    )

@bp.route('edit/<id>', methods=['GET', 'POST'])
@admin_authenticator.route
def edit(id):
    recommandation = db.session.query(Recommandation).get(id)
    if not recommandation:
        abort(404)
    form = FormEdit(obj=recommandation)
    if request.method == "POST" and form.validate():
        form.populate_obj(recommandation)
        db.session.add(recommandation)
        db.session.commit()
        return redirect(url_for("recommandations.list_", **request.args.to_dict(flat=False)))
    return render_template(
        "edit.html",
        form=form,
        action="Éditer",
        recommandation=recommandation
    )

@bp.route('remove/<id>', methods=["GET", "POST"])
@admin_authenticator.route
def remove(id):
    recommandation = Recommandation.query.get(id)
    if request.method == "POST":
        recommandation.delete()
        db.session.commit()
        flash("Recommandation supprimée")
        return redirect(url_for("recommandations.list_"))
    return render_template(
        "remove.html",
        id=id,
        recommandation=recommandation
    )


def make_query(form):
    query = Recommandation.query
    if form.search.data:
        search = f"%{form.search.data}%"
        query = query.filter(
            or_(
                    Recommandation.recommandation.ilike(search),
                    Recommandation.precisions.ilike(search),
                    Recommandation.categorie.ilike(search)
            )
        )
    if form.status.data:
        query = query.filter(Recommandation.status==form.status.data)
    else:
        query = query.filter(
            or_(
                Recommandation.status==None,
                Recommandation.status!='deleted'
            )
        )
    for categorie in form.categories.data:
        attr = getattr(Recommandation, categorie)
        if attr.type.python_type == list:
            query = query.filter(func.cardinality(attr) > 0)
        else:
            query = query.filter(attr.is_(True))

    if form.type.data is not None and form.type.data != "None":
        query = query.filter(Recommandation.type_==form.type.data)
    if form.order.data == 'random':
        return query.order_by(func.random())
    else:
        return query.order_by(Recommandation.id)

@bp.route('/', methods=["GET", "POST"])
@admin_authenticator.route
def list_():
    form = FormSearch(request.args)
    query = make_query(form)
    return render_template(
        "list.html",
        recommandations=query.all(),
        count=query.count(),
        form=form,
    )

@bp.route('/csv', methods=["GET", "POST"])
@admin_authenticator.route
def csv():
    form = FormSearch(request.args)
    query = make_query(form)

    return Response(
        stream_with_context(
            chain(
                generate_line(Recommandation().to_dict().keys()),
                map(
                    lambda line: generate_line(line.to_dict().values()),
                    query.all()
                )
            )
        ),
        mimetype="text/csv",
        headers={
            "Content-Disposition": f"attachment; filename=recommandations-export-{datetime.now().strftime('%Y-%m-%d_%H%M')}.csv"
        }
    )

@bp.route('/<id>/details')
@admin_authenticator.route
def details(id):
    recommandation = Recommandation.query.get(id)
    if not recommandation:
        return abort(404)

    newsletters = NewsletterDB.query\
        .filter_by(recommandation_id=id)\
        .filter(NewsletterDB.appliquee.isnot(None))\
        .order_by(NewsletterDB.date.desc())\
        .all()

    return render_template(
        "details.html",
        recommandation=recommandation,
        newsletters=newsletters,
    )

ecosante/recommandations/templates/details.html
{% extends "base_admin.html" %}

{% block content %}

<section class="section">
    <div class="container">
    <article class="article article__preview panel">
        <h6 class="article__title">Recommandation</h6>
        <div>
            {{ recommandation.recommandation}}
        </div>
        <h6 class="article__title">Précisions</h6>
        <div>
            {{ recommandation.precisions}}
        </div>
        <a class="button" href="{{ url_for("recommandations.edit", id=recommandation.id) }}">Éditer</a>
    </article>
    {% if newsletters %}
    {% set nb_avis_positifs = newsletters|selectattr("appliquee")|select("equalto", "oui")|list|count %}
    {% set nb_avis = newsletters|count %}
    {% set percent_avis_positifs = nb_avis_positifs/nb_avis %}
    <h3>{{ "%.2f"|format(percent_avis_positifs|float) }}% de personnes disent appliquer qu’ils vont appliquer cette recommandation</h3>
    <h4>Commentaires sur les avis négatifs</h4>
    <ul>
    {% for nl in newsletters if nl.avis %}
        <li>{{ nl.avis }}</li>
    {% endfor %}
    </ul>
    {% else %}
    Pas encore d'avis
    {% endif %}
    </div>
</section>

{% endblock content %}

ecosante/recommandations/templates/edit.html
{% extends "base_admin_form.html" %}

{% block pre_form %}

{% scss "recommandations/css/edit.scss" %}
  <link href="{{ ASSET_URL }}" rel="stylesheet">
{% endassets %}

{% endblock pre_form %}

{% block block_form %}
{% if form.qa.errors %}
<div class="notification error">
    {{ form.qa.errors[0] }}
</div>
{% endif %}
<div class="row centered_row">
    <form method="POST" name="editForm">
        {{ form.hidden_tag() }}
        <div class="panel">
            <h4 class="subtitle">Recommandation</h4>
            {{ render_field(form.status) }}
            {{ render_field(form.recommandation) }}
            <div class="apercu">
                <button class="button small button-apercu" data-id="recommandation">Apercu</button>
                <div class="rendu modal"></div>
            </div>
            {{ render_field(form.precisions) }}
            <div class="apercu">
                <button class="button small button-apercu" data-id="precisions">Apercu</button>
                <div class="rendu modal"></div>
            </div>
            {{ render_field(form.type_) }}
            <div class="form__group">
                <button class="button" type="submit" id="submit">{{ action }}</button>
                <button class="button-outline primary raz">RàZ du panel</button>
            </div>
        </div>
        <div class="panel" id="pollens">
            <h4 class="subtitle">Pollens</h4>
            {{ render_field(form.min_raep) }}
            {{ render_field(form.qa) }}
            <div class="form__group">
                <button class="button" type="submit" id="submit">{{ action }}</button>
                <button class="button-outline primary raz">RàZ du panel</button>
            </div>
        </div>
        <div class="panel" id="episode_pollution">
            <h4 class="subtitle">Polluants</h4>
            {{ render_field(form.polluants) }}
            {{ render_field(form.etat_episode_pollution) }}
            <div class="form__group">
                <button class="button" type="submit" id="submit">{{ action }}</button>
                <button class="button-outline primary raz">RàZ du panel</button>
            </div>
        </div>
        <div class="panel" id="indice_atmo">
            <h4 class="subtitle">Précisions pour l’indice ATMO</h4>
            {{ render_field(form.saison) }}
            {{ render_field(form.qa) }}
            <div class="form__group">
                <button class="button" type="submit" id="submit">{{ action }}</button>
                <button class="button-outline primary raz">RàZ du panel</button>
            </div>
        </div>
        <div class="panel" id="radon">
            <h4 class="subtitle">Précisions pour le potentiel radon</h4>
            {{ render_field(form.potentiel_radon) }}
            <div class="form__group">
                <button class="button" type="submit" id="submit">{{ action }}</button>
                <button class="button-outline primary raz">RàZ du panel</button>
            </div>
        </div>
        <div class="panel" id="vigilance_meteo">
            <h4 class="subtitle">Précisions pour la vigilance météo</h4>
            {{ render_field(form.vigilance_couleur_ids) }}
            {{ render_field(form.vigilance_phenomene_ids) }}
            <div class="form__group">
                <button class="button" type="submit" id="submit">{{ action }}</button>
                <button class="button-outline primary raz">RàZ du panel</button>
            </div>
        </div>
        <div class="panel" id="indice_uv">
            <h4 class="subtitle">Indice UV</h4>
            {{ render_field(form.min_indice_uv) }}
            <div class="form__group">
                <button class="button" type="submit" id="submit">{{ action }}</button>
                <button class="button-outline primary raz">RàZ du panel</button>
            </div>
        </div>
        <div class="panel" id="inscription">
            <h4 class="subtitle">Inscription</h4>
            {{ render_field(form.population) }}
            {{ render_field(form.activites) }}
            {{ render_field(form.deplacement) }}
            {{ render_field(form.chauffage) }}
            {{ render_field(form.animal_de_compagnie) }}
            <div class="form__group">
                <button class="button" type="submit" id="submit">{{ action }}</button>
                <button class="button-outline primary raz">RàZ du panel</button>
            </div>
        </div>
        <div class="panel">
            <h4 class="subtitle">Misc</h4>
            {{ render_field(form.ordre) }}
            {{ render_field(form.sources) }}
            {{ render_field(form.categorie) }}
            <div class="form__group">
                <button class="button" type="submit" id="submit">{{ action }}</button>
                <button class="button-outline primary raz">RàZ du panel</button>
            </div>
        </div>
    </form>
</div>

{% rollupjs "recommandations/js/edit.js" %}
<script src="{{ ASSET_URL}}"></script>
{% endassets %}
{% endblock block_form %}

ecosante/recommandations/templates/list.html
{% extends 'base_admin_form.html'%}

{% block block_form %}
{% scss "recommandations/css/list.scss" %}
  <link href="{{ ASSET_URL }}" rel="stylesheet">
{% endassets %}

<div class="section">
    <div class="container">
        <a href="{{ url_for("recommandations.add")}}">Ajouter une recommandation</a>
        <form class="search">
        {{ render_field(form.search) }}
        {{ render_field(form.categories)}}
        {{ render_field(form.status)}}
        {{ render_field(form.type)}}
        <div class="input__group">
            <input type="submit" value="Rechercher">
            <a href="{{ url_for("recommandations.csv", **request.args.to_dict(flat=False)) }}" class="button">Export CSV</a>
        </div>
        </form>
        <ul>
            <h3>Résultat de la recherche</h3>
            <p>{{ count }} recommandations</p>
            {% for recommandation in recommandations %}
            <li>
                <details>
                    <summary> {{ recommandation.recommandation }}</summary>
                    <p> {{ recommandation.precisions}} </p>
                </details>
                <p>
                {% for f in recommandation.filtres %}
                <abbr title="{{ f[2] }}">{{ f[1] }}</span>
                {% endfor %}
                </p>
                <a href="{{ url_for("recommandations.edit", id=recommandation.id, **request.args.to_dict(flat=False)) }}">Éditer</a>
                <a href="{{ url_for("recommandations.remove", id=recommandation.id, **request.args.to_dict(flat=False)) }}">Supprimer</a>
                <a href="{{ url_for("recommandations.details", id=recommandation.id, **request.args.to_dict(flat=False)) }}">Avis</a>
            </li>
        {% endfor %}

        </ul>
    </div>
</div>

{% endblock block_form %}

ecosante/recommandations/templates/remove.html
{% extends "base_admin.html" %}

{% block content %}

<section class="section">
    <div class="container">
        <form method="post" class="form">
        <button class="button" type="submit">Confirmer la suppression</button>
        </form>
        <h5>{{ recommandation.recommandation }}</h5>
        <p>{{ recommandation.precisions }}</p>
        <form method="post">
        <button class="button" type="submit">Confirmer la suppression</button>
        </form>
    </div>
</section>


{% endblock content %}